# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build your docs in a sub-directory with Sphinx
sphinx:
   configuration: docs/conf.py

# If you have additional requirements for building your docs, add them here
python:
   install:
   - requirements: requirements-dev.txt
